/**
 * Route manifest — writes docs/route-manifest.md and .qa/routes.json from
 * the registry of published routes (lib/routes.ts) plus every href carried
 * by article and legal content. The crawl (scripts/qa/crawl.mjs) reads the
 * JSON to assert that the served sitemap equals the manifest and that every
 * content link resolves to a published page.
 *
 *   npx tsx scripts/qa/route-manifest.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { publishedRoutes, isPublishedHref, siteOrigin } from "../../lib/routes";
import { articles } from "../../content/blog";
import { legalDocuments } from "../../content/legal";
import { cityPages } from "../../content/cities";
import { serviceDetailPages } from "../../content/services";
import { blockHrefs, isInternalHref } from "../../content/blocks";

const routes = publishedRoutes();
const contentLinks: { from: string; href: string; ok: boolean }[] = [];
for (const a of articles) for (const href of blockHrefs(a.body)) contentLinks.push({ from: a.path, href, ok: isPublishedHref(href) });
for (const d of legalDocuments) for (const href of blockHrefs(d.body)) contentLinks.push({ from: d.path, href, ok: isPublishedHref(href) });
for (const a of articles) {
  for (const href of a.relatedServices ?? []) contentLinks.push({ from: a.path, href, ok: isPublishedHref(href) });
  for (const slug of a.relatedArticles ?? []) contentLinks.push({ from: a.path, href: `/blog/${slug}`, ok: isPublishedHref(`/blog/${slug}`) });
}
for (const c of cityPages) {
  for (const href of c.services.paths) contentLinks.push({ from: c.path, href, ok: isPublishedHref(href) });
  for (const href of blockHrefs(c.context?.body ?? [])) contentLinks.push({ from: c.path, href, ok: isPublishedHref(href) });
  for (const l of c.related?.links ?? []) contentLinks.push({ from: c.path, href: l.href, ok: isPublishedHref(l.href) });
}
for (const d of serviceDetailPages) {
  if (d.parent) contentLinks.push({ from: d.path, href: d.parent, ok: isPublishedHref(d.parent) });
  for (const l of d.related?.links ?? []) contentLinks.push({ from: d.path, href: l.href, ok: isPublishedHref(l.href) });
}
const badInternal = contentLinks.filter((l) => isInternalHref(l.href) && !l.ok);
const badExternal = contentLinks.filter((l) => !isInternalHref(l.href) && !/^https:\/\//.test(l.href));

const md = (t: string) => t.replace(/\|/g, "\\|");
const lines: string[] = [
  "# Route manifest",
  "",
  "Generated by `npx tsx scripts/qa/route-manifest.ts` from the registries of",
  "published routes. Every path here is implemented; the sitemap is generated",
  "from the same list. Do not edit by hand.",
  "",
  `Routes: ${routes.length} · content links: ${contentLinks.length} · unresolved internal links: ${badInternal.length} · non-https external links: ${badExternal.length}`,
  "",
  "| Path | Kind | Title | Parent | Outgoing relationships | Incoming from | Last modified |",
  "|---|---|---|---|---|---|---|",
  ...routes.map(
    (r) =>
      `| \`${r.path}\` | ${r.kind} | ${md(r.title)} | ${r.links?.parent ? `\`${r.links.parent}\`` : "—"} | ${(r.links?.related ?? []).map((x) => `\`${x}\``).join(", ") || "—"} | ${r.incoming.map((x) => (x.startsWith("/") ? `\`${x}\`` : x)).join(", ")} | ${r.lastModified ?? "unknown (omitted)"} |`
  ),
  "",
  "## Content links (articles, legal documents, city and service-detail pages)",
  "",
  "| From | Href | Resolves |",
  "|---|---|---|",
  ...contentLinks.map((l) => `| \`${l.from}\` | \`${l.href}\` | ${l.ok ? "yes" : "**NO**"} |`),
  "",
];
writeFileSync("docs/route-manifest.md", lines.join("\n"));
mkdirSync(".qa", { recursive: true });
writeFileSync(".qa/routes.json", JSON.stringify({ origin: siteOrigin, routes, contentLinks }, null, 2));
console.log(`manifest: ${routes.length} routes, ${contentLinks.length} content links, ${badInternal.length} unresolved internal, ${badExternal.length} non-https external`);
if (badInternal.length || badExternal.length) {
  for (const l of [...badInternal, ...badExternal]) console.error(`  BAD LINK ${l.from} → ${l.href}`);
  process.exit(1);
}
